#! /bin/sh
# postrm script for ipppd

set -e

case "$1" in
       purge)
         pkg=ipppd
         for conffile in $(ucfq $pkg -w| grep $pkg | cut -f 1 -d ":");do
           ucf --purge $conffile && ucfr --purge $pkg $conffile && rm -f $conffile
           for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
             rm -f $conffile$ext
           done
         done
         ;;

       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
         ;;

    *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 0
	 ;;
esac

# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper mv_conffile /etc/ppp/ip-down.d/99-ipppd /etc/ppp/ip-down.d/ipppd 1:3.25\+dfsg1-3.3 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/ppp/ip-up.d/00-ipppd /etc/ppp/ip-up.d/ipppd 1:3.25\+dfsg1-3.3 -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/11.1.4ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
