#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.4ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d isdnutils-base remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init.d/isdnutils 1:3.25\+dfsg1-3.5\~ -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/11.1.4ubuntu1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
