///*****************************************
//  Copyright (C) 2009-2019
//  ITE Tech. Inc. All Rights Reserved
//  Proprietary and Confidential
///*****************************************
//   @file   <515XRAM.H>
//   @author Jau-Chih.Tseng@ite.com.tw
//   @date   2019/01/03
//   @fileversion: ITE_HDMITX_SAMPLE_3.27
//******************************************/

#ifndef _515xram_
#define _515xram_
/*
#define MySon
#ifdef MySon
extern BYTE xdata  PADMOD0		_at_  0x0f50;
//unsigned char xdata  PADMOD1		_at_  0x0f51;
//unsigned char xdata  PADMOD2		_at_  0x0f52;
extern BYTE xdata  PORT4OE		_at_  0x0f57;
#else
//unsigned char xdata  EDID_WP		_at_  0x00E8;//	PORT40
//unsigned char xdata  EDID1_WP		_at_  0x00E9;//	PORT41
//unsigned char xdata  RX_HPD		_at_  0x00EA;//	PORT42
//unsigned char xdata  RX_HPD1		_at_  0x00EB;// PORT43
#endif
*/
#endif
