obj-$(CONFIG_IT66121_RGB_TO_HDMI) += it6612_module.o

it6612_module-$(CONFIG_IT66121_RGB_TO_HDMI) := it6612.o csc.o hdmitx_cec.o hdmitx_drv.o hdmitx_hdcp.o \
                                                       hdmitx_input.o hdmitx_sys.o sha1.o \
                                                       io.o TimerProcess.o utility.o
KBUILD_CFLAGS   := -w -fno-common


